depromeet/WalWal-server

src/main/java/com/depromeet/stonebed/domain/common/BaseTimeEntity.java
src/main/java/com/depromeet/stonebed/domain/member/dao/MemberRepository.java
src/main/java/com/depromeet/stonebed/domain/member/domain/Member.java
src/main/java/com/depromeet/stonebed/domain/member/domain/MemberRole.java
src/main/java/com/depromeet/stonebed/domain/member/domain/MemberStatus.java
src/main/java/com/depromeet/stonebed/domain/member/domain/OauthInfo.java
src/main/java/com/depromeet/stonebed/domain/member/domain/Profile.java
src/test/java/com/depromeet/stonebed/domain/member/domain/MemberTest.java

- close #10 
- 회원 엔티티 구현
- OAuth를 사용할 것이기에 OAuthProvider, email 추가
- 추후 관리를 위한 ROLE, STATUS enum 타입 추가
- 최근 로그인 일자 트래킹을 위한 lastLoginAt
- 엔티티와 Repository만 중점적으로 봐주시면 될 듯합니당
-

[WALWAL-88] 회원 엔티티 구성

---

src/main/java/com/depromeet/stonebed/domain/member/domain/OauthInfo.java
src/main/java/com/depromeet/stonebed/domain/member/domain/Profile.java

- close #29 
- JPA가 record를 지원하지 않아 클래스로 변경
-
-

[WALWAL-114] record -> class 변경

---

src/main/java/com/depromeet/stonebed/domain/mission/dao/MissionRepository.java
src/main/java/com/depromeet/stonebed/domain/mission/domain/Mission.java

- close #31 
- 미션 엔티티 구현
- 일단 윤찬님이 바로 시작할 수 있도록 이정도 해서 올려보려고 했는데 혹시 더 필요한 부분이 있으면 알려주시면 감사드리겠습니다.
- 그 외 부족한 부분도 봐주시면 감사드립니다 🙇‍♂️
-

[WALWAL-115] 미션 엔티티 구현

---

build.gradle
src/main/java/com/depromeet/stonebed/infra/config/RedisConfig.java
src/main/java/com/depromeet/stonebed/infra/properties/PropertiesConfig.java
src/main/java/com/depromeet/stonebed/infra/properties/RedisProperties.java
src/main/resources/application-redis.yml
src/main/resources/application.yml
src/test/java/com/depromeet/stonebed/StonebedApplicationTests.java
src/test/java/com/depromeet/stonebed/domain/member/domain/MemberTest.java

- close #17 
- redis 환경 구성으로 프로파일링으로 host, port, password를 정의
- 별도의 `@Value` 변수가 아닌 Properties를 구성으로 final 변수 선언
- yml에 대한 프로파일링 분리
- redis Config 코드 외에는 별도 프로파일링 분리한 거 밖엔 없습니다!
-

[WALWAL-105] redis 환경 구성

---

.github/workflows/develop-build-deploy.yml
.github/workflows/develop-pull-request-on-check.yml
Dockerfile
Dockerrun.aws.json

- close #24 
- elastic beanstalk dev 서버 workflow를 작성
- 배포된 elastic beanstalk의 application, environment name 맞추어 진행
- dockerhub로 이미지 빌드 및 푸시 진행
- deployment_package는 Dockerrun.aws.json 과 같이 docker 환경 
- Elastic BeanStalk 배포를 위해 AWS 키와 Docker 키는 Repository secret key에 등록했습니다!
-

[WALWAL-110] elastic beanstalk dev 서버 workflow 작성

---

.github/workflows/develop-build-deploy.yml

- close #40 
-Elastic BeanStalk 배포 version 배포 시점으로 라벨링
-
-

[WALWAL-123] Elastic BeanStalk 배포 version Label

---

src/main/java/com/depromeet/stonebed/domain/auth/application/AuthService.java
src/main/java/com/depromeet/stonebed/domain/auth/dto/request/RefreshTokenRequest.java
src/main/java/com/depromeet/stonebed/domain/member/application/MemberService.java
src/main/java/com/depromeet/stonebed/domain/member/domain/Member.java
src/main/java/com/depromeet/stonebed/domain/member/dto/request/CreateMemberRequest.java

- close #73 
- 온보딩 페이지에 대한 분기처리
- 토큰의 임시 토큰 여부 판별
- 소셜 로그인 여부 판별
-

[WALWAL-161] 임시 토큰 여부 판별

---

src/main/java/com/depromeet/stonebed/domain/auth/api/AuthController.java
src/main/java/com/depromeet/stonebed/domain/auth/application/AuthService.java
src/main/java/com/depromeet/stonebed/domain/auth/application/JwtTokenService.java
src/main/java/com/depromeet/stonebed/domain/member/domain/Member.java
src/main/java/com/depromeet/stonebed/global/error/ErrorCode.java

- close #70 
- 회원탈퇴 기능으로 redis 초기화, 회원 상태 DELETED로 갱신 
-
-

[WALWAL-157] 회원탈퇴 API

---

.github/workflows/production-build-deploy.yml
src/main/java/com/depromeet/stonebed/domain/auth/application/apple/AppleClient.java

- close #65 
- 운영 서버 워크플로를 작성
- versioning 태그를 사용하여 배포
- 그 외 Profiling에 따른 AppleClient 환경 분리
-

[WALWAL-154] PROD 운영 서버 워크플로 작성

---

.github/workflows/develop-build-deploy.yml
.github/workflows/production-build-deploy.yml
Dockerfile
docker-compose.yaml

- close #88 
- EB에서 자동으로 컨테이너가 다운되는 현상으로
- 기존 EB를 종료시키고 임시로 단일 EC2 서버로 배포
-
-

hotfix: EC2 도커 단일 인스턴스 배포

---

src/main/java/com/depromeet/stonebed/domain/follow/api/FollowController.java
src/main/java/com/depromeet/stonebed/domain/follow/application/FollowService.java
src/main/java/com/depromeet/stonebed/domain/follow/dao/FollowRepository.java
src/main/java/com/depromeet/stonebed/domain/follow/domain/Follow.java
src/main/java/com/depromeet/stonebed/domain/follow/dto/request/FollowCreateRequest.java
src/main/java/com/depromeet/stonebed/domain/follow/dto/request/FollowDeleteRequest.java
src/main/java/com/depromeet/stonebed/domain/follow/dto/response/FollowRelationMemberResponse.java
src/main/java/com/depromeet/stonebed/domain/follow/dto/response/FollowStatus.java
src/main/java/com/depromeet/stonebed/domain/follow/dto/response/FollowedMemberResponse.java
src/main/java/com/depromeet/stonebed/domain/follow/dto/response/FollowerDeletedResponse.java
src/main/java/com/depromeet/stonebed/global/error/ErrorCode.java
src/test/java/com/depromeet/stonebed/domain/follow/application/FollowServiceTest.java

- close #69 
- 팔로우 기능 추가
- 팔로우 추가 및 취소, 조회가 가능하며 그에 따른 Status를 return
-
-

[WALWAL-156] 팔로우 추가 및 취소, 조회 기능

---

src/main/java/com/depromeet/stonebed/domain/member/api/MemberController.java
src/main/java/com/depromeet/stonebed/domain/member/application/MemberService.java
src/main/java/com/depromeet/stonebed/domain/member/dao/MemberRepository.java
src/main/java/com/depromeet/stonebed/domain/member/dto/request/NicknameCheckRequest.java
src/main/java/com/depromeet/stonebed/global/error/ErrorCode.java

- close #80 
- 닉네임 검증하는 API
- 닉네임은 특수문자, 공백 포함 2자 이상, 14자 이하
-
-

[WALWAL-164] 닉네임 검증

---

src/main/java/com/depromeet/stonebed/domain/mission/api/MissionController.java
src/main/java/com/depromeet/stonebed/domain/missionRecord/api/MissionRecordController.java

- close #78 
- 간단한 스웨거 문서 이름 변경
-
-

[WALWAL-163] 스웨거 문서 이름 일관적으로 포매팅

---

src/test/java/com/depromeet/stonebed/global/util/SecurityUtilTest.java

- close #96 
- SecurityUtil 클래스에 대한 테스트 코드 작성
-
-

test: SecurityUtil 테스트 코드 추가

---

.github/workflows/develop-build-deploy.yml
.github/workflows/develop-pull-request-on-check.yml
.github/workflows/production-build-deploy.yml
docker-compose-test.yaml
src/test/java/com/depromeet/stonebed/TestRedisConfig.java
src/test/java/com/depromeet/stonebed/domain/auth/dao/RefreshTokenRepositoryTest.java

- close #97 
- Redis를 사용하는 RefreshToken에 대한 테스트 코드
- container에 test를 위한 testContainer compose를 생성하여 구성
-
-

test: RefreshToken 테스트

---

src/main/java/com/depromeet/stonebed/domain/member/application/MemberService.java
src/main/java/com/depromeet/stonebed/domain/member/dto/request/CreateMemberRequest.java

- close #94 
- 온보딩 시 default ImageUrl 필드 추가
-
-

fix: 온보딩 Default imageUrl 요청 필드 추가

---

src/main/java/com/depromeet/stonebed/domain/missionRecord/api/MissionRecordController.java
src/main/java/com/depromeet/stonebed/domain/missionRecord/application/MissionRecordService.java
src/main/java/com/depromeet/stonebed/domain/missionRecord/domain/MissionRecord.java
src/main/java/com/depromeet/stonebed/domain/missionRecord/dto/request/MissionRecordSaveRequest.java
src/test/java/com/depromeet/stonebed/domain/missionRecord/MissionRecordServiceTest.java

- close #102 
- 미션기록 저장 시 Text값 추가
- Text값이 null 이어도 저장됨
-
-

[WALWAL-168] MissionRecord에 Text값 추가

---

src/test/java/com/depromeet/stonebed/global/util/MemberUtilTest.java

- close #95 
- MemberUtil에 대한 테스트 코드 작성
- 선행 작업으로 #57 먼저 Merge가 되어야 한다.
-
-

test: MemberUtil 테스트 코드 추가

---

.github/workflows/develop-build-deploy.yml
.github/workflows/production-build-deploy.yml

chore: prod workflow 작성

---

src/main/java/com/depromeet/stonebed/global/config/security/WebSecurityConfig.java

- close #111 
- 배포된 운영환경에서 Swagger 접속하도록 변경
-
-

fix: prod 환경 Swagger 동작

---

src/main/java/com/depromeet/stonebed/domain/feed/api/FeedController.java
src/main/java/com/depromeet/stonebed/domain/feed/application/FeedService.java
src/main/java/com/depromeet/stonebed/domain/feed/dao/FeedRepository.java
src/main/java/com/depromeet/stonebed/domain/feed/dao/FeedRepositoryCustom.java
src/main/java/com/depromeet/stonebed/domain/feed/dao/FeedRepositoryImpl.java
src/main/java/com/depromeet/stonebed/domain/feed/dto/request/FeedGetRequest.java
src/main/java/com/depromeet/stonebed/domain/feed/dto/response/FeedContentGetResponse.java
src/main/java/com/depromeet/stonebed/domain/feed/dto/response/FeedGetResponse.java
src/test/java/com/depromeet/stonebed/domain/feed/application/FeedServiceTest.java

- close #83 
- 피드 구현 GET /feed/
- 일단 테스트했을 때 기능은 되는데 문제점이나 개선사항 알려주면 반영하겠습니다 ㅠㅜ
-

[WALWAL-159] 피드 작업

---

src/main/java/com/depromeet/stonebed/domain/missionRecord/application/MissionRecordScheduledService.java
src/main/java/com/depromeet/stonebed/domain/missionRecord/application/MissionRecordService.java
src/main/java/com/depromeet/stonebed/domain/missionRecord/dao/MissionRecordRepository.java
src/main/java/com/depromeet/stonebed/domain/missionRecord/dao/MissionRecordRepositoryCustom.java
src/main/java/com/depromeet/stonebed/domain/missionRecord/dao/MissionRecordRepositoryImpl.java

- close #116 
- 현재 미션을 시작하면 상태가 IN_PROGRESS로 변경되는데 이 상태에서 하루가 지나가면 상태가 계속 IN_PROGRESS로 되있기때문에 매일 정각 오늘의 미션을 제공해줄때 같이 호출하여 IN_PROGRESS -> NOT_COMPLETED로 상태변경
- 매일 00시 00분 00초에 해당 메서드를 실행하는 스케쥴러 구현
-
-

[WALWAL-170] 매일 IN_PROGRESS -> NOT_COMPLETED로 변경해주는 스케쥴러 구현

---

src/main/java/com/depromeet/stonebed/domain/missionRecord/api/MissionRecordController.java
src/main/java/com/depromeet/stonebed/domain/missionRecord/dto/request/MissionRecordSaveRequest.java
src/main/java/com/depromeet/stonebed/domain/missionRecord/dto/request/MissionRecordStartRequest.java
src/test/java/com/depromeet/stonebed/domain/missionRecord/MissionRecordServiceTest.java

- close #123 
- restful한 구조를 위해 request path 파라메터에서 쿼리 파라메터로 변경
- breaking change가 있어요
-

refactor: MissionRecord API `Path` -> `Query`/`Body` 로 수정

---

src/main/java/com/depromeet/stonebed/domain/auth/api/AuthController.java
src/main/java/com/depromeet/stonebed/domain/auth/application/AuthService.java
src/main/java/com/depromeet/stonebed/domain/member/domain/Member.java
src/test/java/com/depromeet/stonebed/domain/member/domain/MemberTest.java

fix: withdraw temporary role 갱신

---

build.gradle
src/main/resources/application-actuator.yml

chore: prometheus 구성

---

src/main/java/com/depromeet/stonebed/domain/member/api/MemberController.java
src/main/java/com/depromeet/stonebed/domain/member/application/MemberService.java
src/main/java/com/depromeet/stonebed/domain/member/dto/request/MemberProfileUpdateRequest.java
src/test/java/com/depromeet/stonebed/domain/member/application/MemberServiceTest.java

- close #126 
- 회원 프로필 수정으로 닉네임, 프로필 이미지를 인자로 받아 갱신 처리
- 갱신을 위한 PUT 요청으로 구현
-
-

feat: 프로필 수정

---

src/main/java/com/depromeet/stonebed/domain/fcm/application/FcmScheduledService.java
src/main/java/com/depromeet/stonebed/domain/fcm/application/FcmService.java
src/main/java/com/depromeet/stonebed/domain/missionRecord/api/MissionRecordController.java
src/main/java/com/depromeet/stonebed/domain/missionRecord/application/MissionRecordService.java
src/main/java/com/depromeet/stonebed/domain/missionRecord/dto/response/MissionRecordCompleteTotal.java
src/test/java/com/depromeet/stonebed/domain/missionRecord/MissionRecordServiceTest.java

- close #131 
- totalCount 조회 메서드를 POST -> GET으로 변경
- totalCount 조회에 대한 Long이 아닌 DTO 레코드 변경
- FCM Service중 잠수함 패치 사항있어용
-

fix: totalCount DTO 변환

---

src/main/java/com/depromeet/stonebed/domain/image/api/ImageController.java
src/main/java/com/depromeet/stonebed/domain/image/application/ImageService.java
src/main/java/com/depromeet/stonebed/domain/image/domain/ImageType.java
src/main/java/com/depromeet/stonebed/domain/image/dto/request/MissionImageCreateRequest.java
src/main/java/com/depromeet/stonebed/domain/image/dto/request/MissionImageUploadRequest.java
src/main/java/com/depromeet/stonebed/domain/mission/application/MissionService.java
src/main/java/com/depromeet/stonebed/domain/mission/domain/Mission.java
src/main/java/com/depromeet/stonebed/domain/missionRecord/api/MissionRecordController.java
src/main/java/com/depromeet/stonebed/domain/missionRecord/dto/request/MissionRecordSaveRequest.java
src/test/java/com/depromeet/stonebed/domain/missionRecord/MissionRecordServiceTest.java

- close #120 
- 미션 기록 부분 text -> content 문구 변경
- 미션 이미지 업로드 API 및 Presigned URL 생성 API 구현
-
-

[WALWAL-171] mission image upload

---

src/main/java/com/depromeet/stonebed/domain/auth/application/AuthService.java
src/main/java/com/depromeet/stonebed/domain/member/domain/Member.java
src/test/java/com/depromeet/stonebed/domain/auth/application/AuthServiceTest.java

- close #140 
- 영속성 컨텍스트 내부에서 반영이 제대로 이뤄지지 않아 flush를 사용해 해결.
-
-

fix: MemberRole 반영이 되지 않는 현상

---

src/main/java/com/depromeet/stonebed/domain/feed/dto/response/FeedContentGetResponse.java

- close #143 
- 피드 API에 프로필 정보와 미션 정보 추가
- DTO 변경만 있어용 profile이 Embedded로 구현돼있더라구요
-

feature: 피드 사용자 닉네임 프로필 정보 추가 및 미션 이름 추가

---

docker-compose.yaml

- close #150 
- nginx/log 마운트추가
-
-

chore: nginx log추가

---

src/main/java/com/depromeet/stonebed/domain/member/application/MemberService.java
src/main/java/com/depromeet/stonebed/domain/member/dao/MemberRepository.java
src/main/java/com/depromeet/stonebed/domain/member/dao/MemberRepositoryCustom.java
src/main/java/com/depromeet/stonebed/domain/member/dao/MemberRepositoryImpl.java

- close #153 
- 닉네임 검증이 올바르게 되어지지 않아 수정
-
-

fix: 닉네임 검증 로직 수정

---

.github/workflows/develop-build-deploy.yml
.github/workflows/develop-pull-request-on-check.yml

- close #155 
- PR 업 시 build 단계에서 이미 spotlessCheck가 이뤄지고 있어서 불필요한 job 삭제
- deploy 워크플로 잠수함 패치
-
-

fix: PR 업 워크플로 수정

---

src/main/java/com/depromeet/stonebed/domain/fcm/application/FcmTokenService.java
src/main/java/com/depromeet/stonebed/global/error/ErrorCode.java

- close #157 
- 같은 디바이스에서 로그인을 다양하게 할 때 동일한 fcm_token 저장 시 삭제 후 저장 
-
-

fix: 동일한 fcm_token 저장 오류 해결

---

src/main/java/com/depromeet/stonebed/domain/feed/application/FeedService.java
src/main/java/com/depromeet/stonebed/domain/feed/dao/FeedRepositoryImpl.java
src/main/java/com/depromeet/stonebed/global/error/ErrorCode.java
src/test/java/com/depromeet/stonebed/domain/feed/application/FeedServiceTest.java

- close #160
- 커서 파싱 오류 해결
- 본인 기록만 나오는 문제 해결
- 코드 짜면서 멤버를 필터링하는 걸 왜 넣었는지... 정신이 없었던 것 같습니다ㅜ
-

fix: 피드 커서 파싱 오류 핸들링 및 본인 기록만 나오는 문제 해결

---

src/main/java/com/depromeet/stonebed/domain/member/api/MemberController.java
src/main/java/com/depromeet/stonebed/domain/member/application/MemberService.java
src/main/java/com/depromeet/stonebed/domain/member/dto/response/MemberInfoResponse.java
src/test/java/com/depromeet/stonebed/domain/member/application/MemberServiceTest.java

- close #159 
- 회원 정보 GET API DTO 수정
-
-

refactor: 회원 정보 DTO

---

src/main/java/com/depromeet/stonebed/domain/fcm/domain/FcmToken.java

- close #165 
- fcm_tokne nullable=true처리
-
-

fix: nullable=true처리

---

src/main/java/com/depromeet/stonebed/domain/fcm/domain/FcmToken.java

- close #
- token nullable true..
-
-

fix: FCM token nullable true

---

src/main/java/com/depromeet/stonebed/domain/image/application/ImageService.java

- close #
- image_find에서 recordId가 아닌 memberId로 되있어서 수정
-
-

hotifx: mission_image 업로드 수정

---

src/main/resources/application-prod.yml

- close #181 
- DB 업데이트 이후 none 또는 validate로 변경
-
-

chore: prod ddl-auto update

---

src/main/java/com/depromeet/stonebed/domain/image/application/ImageService.java
src/main/java/com/depromeet/stonebed/domain/missionRecord/application/MissionRecordService.java

- close #188 
- 미션 기록 메서드에서 트랜잭션 중첩되는 부분 PRGOPAGATION.REQUIRES_NEW설정 
-
-

미션 기록 트랜잭션 전파수준 설정

---

src/main/java/com/depromeet/stonebed/domain/fcm/api/FcmController.java
src/main/java/com/depromeet/stonebed/domain/fcm/application/FcmScheduledService.java
src/main/java/com/depromeet/stonebed/domain/missionRecord/dao/MissionRecordRepository.java
src/test/java/com/depromeet/stonebed/domain/fcm/application/FcmScheduledServiceTest.java

- close #190 
- 기존 날짜 상관없이 status가 NOT_COMPLETED일 경우 리마인드 알림을 보냈는데, 오늘 날짜기준으로 COMPLETED아닌 대상으로만 리마인드알림 보내게 수정
- 리마인드 알림이 IN_PROGRESS, NOT_COMPLETED인 경우 둘다 보내게 해놨는데 이 부분에 대해서 어떻게 생각하시나요? 
-

Fcm 리마인드 알림 조건 수정

---

src/main/java/com/depromeet/stonebed/domain/missionRecord/api/MissionRecordController.java
src/main/java/com/depromeet/stonebed/domain/missionRecord/application/MissionRecordScheduledService.java
src/main/java/com/depromeet/stonebed/domain/missionRecord/application/MissionRecordService.java
src/main/java/com/depromeet/stonebed/domain/missionRecord/dao/MissionRecordRepositoryCustom.java
src/main/java/com/depromeet/stonebed/domain/missionRecord/dao/MissionRecordRepositoryImpl.java
src/test/java/com/depromeet/stonebed/domain/missionRecord/application/MissionRecordServiceTest.java

refactor: 다른 유저 complete totalCount 조회

---

src/main/java/com/depromeet/stonebed/domain/fcm/api/FcmController.java
src/main/java/com/depromeet/stonebed/domain/missionRecord/api/MissionRecordController.java

- close #212 
- 미션 기록, Fcm 컨트롤러 메서드 명 수정
-
-

미션 기록, Fcm 컨트롤러 메서드 명 수정

---

src/main/java/com/depromeet/stonebed/domain/feed/api/FeedController.java
src/main/java/com/depromeet/stonebed/domain/feed/dto/request/FeedGetRequest.java

- close #210
- 쿼리 파라메터를 받을 때 DTO로 받도록 수정했습니다.
- 앞으로 이렇게 맞춥시다!
-

refactor: 피드 API 쿼리 파라메터 검증 코드 리팩토링

---

src/main/java/com/depromeet/stonebed/domain/image/application/ImageService.java
src/main/java/com/depromeet/stonebed/global/error/ErrorCode.java

- close #216 
- 이미지 Url 생성 후 메서드 호출 하기 전에 null 체크 검증
-
-

ImageUrl null 체크검증

---

src/main/java/com/depromeet/stonebed/domain/missionRecord/application/MissionRecordService.java
src/main/java/com/depromeet/stonebed/domain/missionRecord/dto/response/MissionTabResponse.java

- close #218 
- MissionRecord TabResponse에서 recordId 제거했습니다.
-
-

MissionRecord TabResponse recordId 제거

---

src/main/java/com/depromeet/stonebed/domain/missionRecord/application/MissionRecordService.java
src/main/java/com/depromeet/stonebed/domain/missionRecord/dao/MissionRecordRepositoryImpl.java

- close #221 
- 미션 기록 진행중 -> NOT_COMPLETED 상태변경 안되는 조건 수정
- endOfYesterday 변수를 static final로 선언하니 동적으로 변경되지 않는 문제 발생
- 
-

미션 기록 NOT_COMPLETED 스케쥴러 시간 기준으로 변경

---

src/test/java/com/depromeet/stonebed/domain/missionRecord/application/MissionRecordServiceTest.java

- close #223 
- 미션 완료 화면, 미션 진행 중 화면, 미션 시작 안한 화면 세 케이스에 대해서 테스트 코드 작성했습니다
-
-

미션 탭바 관련 테스트 코드 작성

---

.gitignore
src/main/java/com/depromeet/stonebed/domain/auth/application/AuthService.java
src/main/java/com/depromeet/stonebed/domain/auth/application/kakao/KakaoClient.java
src/main/java/com/depromeet/stonebed/domain/member/api/MemberController.java
src/main/java/com/depromeet/stonebed/domain/member/application/MemberService.java
src/main/java/com/depromeet/stonebed/domain/member/dao/MemberRepository.java
src/main/java/com/depromeet/stonebed/domain/member/domain/Member.java
src/main/java/com/depromeet/stonebed/domain/member/domain/OauthInfo.java
src/test/java/com/depromeet/stonebed/domain/auth/application/AuthServiceTest.java
src/test/java/com/depromeet/stonebed/domain/member/application/MemberServiceTest.java

- close #225 
- 다른 유저의 프로필 조회 API 구현
-
-

feat: 회원 정보 조회 API

---

src/main/java/com/depromeet/stonebed/domain/member/application/MemberService.java
src/main/java/com/depromeet/stonebed/domain/member/dao/MemberRepositoryCustom.java
src/main/java/com/depromeet/stonebed/domain/member/dao/MemberRepositoryImpl.java
src/main/java/com/depromeet/stonebed/global/util/MemberUtil.java
src/test/java/com/depromeet/stonebed/domain/member/application/MemberServiceTest.java
src/test/java/com/depromeet/stonebed/global/util/MemberUtilTest.java

- close #228 
- 본인 닉네임에 대한 검증은 제외하도록 수정
-
-

fix: 본인 nickname 검증

---

src/main/java/com/depromeet/stonebed/domain/feed/dto/response/FeedContentGetResponse.java
src/main/java/com/depromeet/stonebed/domain/mission/application/MissionService.java
src/main/java/com/depromeet/stonebed/domain/mission/domain/Mission.java
src/main/java/com/depromeet/stonebed/domain/mission/dto/request/MissionCreateRequest.java
src/main/java/com/depromeet/stonebed/domain/mission/dto/request/MissionUpdateRequest.java
src/main/java/com/depromeet/stonebed/domain/mission/dto/response/MissionCreateResponse.java
src/main/java/com/depromeet/stonebed/domain/mission/dto/response/MissionGetOneResponse.java
src/main/java/com/depromeet/stonebed/domain/mission/dto/response/MissionUpdateResponse.java
src/test/java/com/depromeet/stonebed/domain/mission/api/MissionControllerTest.java
src/test/java/com/depromeet/stonebed/domain/mission/application/MissionServiceTest.java
src/test/java/com/depromeet/stonebed/domain/mission/dao/MissionHistoryRepositoryTest.java
src/test/java/com/depromeet/stonebed/domain/mission/dao/MissionRepositoryTest.java

- close #234
- 미션 `complete_message` 필드 추가
- 피드 응답에 `missionCompleteMessage` 필드 추가
- 미션 테스트코드 fixture monkey로 변경
- 스키마 변경 작업입니다
-

feature: 피드 미션완료 필드 추가

---

src/main/java/com/depromeet/stonebed/domain/missionRecord/application/MissionRecordService.java
src/main/java/com/depromeet/stonebed/global/error/ErrorCode.java
src/test/java/com/depromeet/stonebed/domain/missionRecord/application/MissionRecordServiceTest.java

- close #214 
- 기획에 따라 내 피드인 경우 부스트가 불가능 하도록 400 Bad Request 응답
- TODO 테스트코드 수정
- 슬랙 스레드 ([링크](https://depromeet-15th.slack.com/archives/C0753TZ01D1/p1724414244652399))
- 오류 코드 이름 괜찮은 지 봐주세용
-

feature: 내 피드인 경우 예외 400 (Bad Request) 처리 추가

---

src/main/java/com/depromeet/stonebed/domain/member/domain/OauthInfo.java

- close #247 
- unique 제약 조건으로 인해 회원탈퇴 후 재회원가입이 적절히 잘 안되는 현상 수정
-
-

hotfix: oauth_email unique 제약 조건 삭제

---

src/main/java/com/depromeet/stonebed/domain/fcm/api/FcmController.java
src/main/java/com/depromeet/stonebed/domain/fcm/application/FcmNotificationService.java
src/main/java/com/depromeet/stonebed/domain/fcm/application/FcmScheduledService.java
src/main/java/com/depromeet/stonebed/domain/fcm/dao/FcmNotificationRepository.java
src/main/java/com/depromeet/stonebed/domain/fcm/dao/FcmRepository.java
src/main/java/com/depromeet/stonebed/domain/missionRecord/dao/MissionRecordRepository.java
src/main/java/com/depromeet/stonebed/global/common/constants/FcmNotificationConstants.java
src/test/java/com/depromeet/stonebed/domain/fcm/application/FcmNotificationServiceTest.java
src/test/java/com/depromeet/stonebed/domain/fcm/application/FcmScheduledServiceTest.java

- close #245 
- 기존 부스터 알림 기능은 500개 Or 5000개 일때만 보내게 되있어서 이 부분 수정했습니다.
- 그리고 500개 이상일 때 알림 메시지가 1번만 가야되기때문에 Boolean으로 체크로직 넣었습니다.
-
-

FCM 부스터 알림 기능 로직 수정

---

src/main/java/com/depromeet/stonebed/domain/fcm/api/FcmController.java
src/main/java/com/depromeet/stonebed/domain/fcm/domain/FcmNotification.java
src/main/java/com/depromeet/stonebed/domain/fcm/dto/response/FcmNotificationDto.java

- close #252 
- FCM 알림리스트 조회 시 BOOSTER일경우 deeplink 추가
-
-

FCM 알림리스트 조회 시 deeplink 추가

---

src/main/java/com/depromeet/stonebed/domain/auth/application/AuthService.java

- close #260 
- register API 내 default image 값 갱신
-
-

fix: 회원가입 시 default image 갱신

---

src/main/java/com/depromeet/stonebed/domain/feed/dao/FeedRepositoryImpl.java
src/main/java/com/depromeet/stonebed/domain/missionRecord/application/MissionRecordService.java
src/main/java/com/depromeet/stonebed/domain/missionRecord/dao/MissionRecordRepositoryCustom.java
src/main/java/com/depromeet/stonebed/domain/missionRecord/dao/MissionRecordRepositoryImpl.java
src/main/java/com/depromeet/stonebed/domain/missionRecord/domain/MissionRecord.java
src/main/java/com/depromeet/stonebed/domain/missionRecord/domain/MissionRecordBoost.java
src/main/java/com/depromeet/stonebed/domain/missionRecord/domain/MissionRecordDisplay.java
src/test/java/com/depromeet/stonebed/domain/missionRecord/application/MissionRecordServiceTest.java

- close #258 
- display 필드 추가
- 필드 추가에 따른 feed, calendar 조건 수정
-
-

feat: 미션 기록 display 필드 추가 및 로직 변경

---

src/main/java/com/depromeet/stonebed/domain/auth/application/AuthService.java

fix: 회원가입 시 image null 처리

---

src/main/java/com/depromeet/stonebed/domain/comment/dao/CommentRepository.java
src/main/java/com/depromeet/stonebed/domain/comment/domain/Comment.java

- close #250 
- 댓글 엔티티 구현으로 부모 댓글 parent_id, 자식은 children OneToMany로 지정
-
-

feat: 댓글 엔티티 구현

---

src/main/java/com/depromeet/stonebed/domain/missionRecord/api/MissionRecordController.java
src/main/java/com/depromeet/stonebed/domain/missionRecord/application/MissionRecordService.java
src/main/java/com/depromeet/stonebed/domain/missionRecord/dao/MissionRecordRepositoryCustom.java
src/main/java/com/depromeet/stonebed/domain/missionRecord/dao/MissionRecordRepositoryImpl.java
src/main/java/com/depromeet/stonebed/domain/missionRecord/dto/response/MissionRecordTabListResponse.java
src/main/java/com/depromeet/stonebed/domain/missionRecord/dto/response/MissionTabResponse.java
src/test/java/com/depromeet/stonebed/domain/missionRecord/application/MissionRecordServiceTest.java

- close #280 
- 미션 탭에서 완료 기록에 대한 list로 Response
- 조건은 issue의 `이번 달`의 조건 추가
- Querydsl의 Projections로 DTO 정의
-
-

feat: 미션 기록 완료 리스트

---

src/main/java/com/depromeet/stonebed/domain/missionRecord/api/MissionRecordController.java
src/main/java/com/depromeet/stonebed/domain/missionRecord/application/MissionRecordService.java
src/main/java/com/depromeet/stonebed/domain/missionRecord/dto/response/MissionRecordTabListResponse.java

- close #283 
- GET /records status 필드 추가
-
-

fix: missionRecordStatus 필드 추가

---

src/main/java/com/depromeet/stonebed/domain/discord/application/DiscordNotificationService.java
src/main/java/com/depromeet/stonebed/domain/report/application/ReportService.java
src/main/java/com/depromeet/stonebed/global/error/ErrorCode.java
src/main/java/com/depromeet/stonebed/infra/properties/DiscordProperties.java
src/main/java/com/depromeet/stonebed/infra/properties/PropertiesConfig.java
src/main/resources/application.yml

- close #286 
- 피드 신고시 discord 알림 기능 구현
-
-

피드 신고시 discord 알림 기능 구현

---

src/main/java/com/depromeet/stonebed/domain/feed/dao/FeedRepositoryImpl.java
src/main/java/com/depromeet/stonebed/domain/feed/dto/FindFeedDto.java
src/main/java/com/depromeet/stonebed/domain/feed/dto/response/FeedContentGetResponse.java
src/main/java/com/depromeet/stonebed/domain/missionRecord/domain/MissionRecord.java
src/test/java/com/depromeet/stonebed/domain/feed/application/FeedServiceTest.java

- close #289 
- 피드 댓글 count 필드 추가했습니다.
- 특별한 이슈는 없었고, 기존 Projections에서 필드 하나 추가했어요.
-
-

feat: 피드 댓글 count 추가

---

src/main/java/com/depromeet/stonebed/domain/mission/domain/Mission.java
src/main/java/com/depromeet/stonebed/domain/missionRecord/dao/MissionRecordRepositoryImpl.java

- close #293 
- 미션 완료 전과 완료 후에 대한 별도 이미지 처리를 위해 complete_image_url 컬럼 추가
- 별도의 이미지 업로드 기능은 구현하지 않음
- 직접 S3 경로에 추가하여 DB에 insert
-
-

feat: 미션 완료 image url 컬럼 추가

---

src/main/java/com/depromeet/stonebed/domain/comment/application/CommentService.java
src/main/java/com/depromeet/stonebed/domain/fcm/application/FcmNotificationService.java
src/main/java/com/depromeet/stonebed/domain/fcm/domain/FcmNotification.java
src/main/java/com/depromeet/stonebed/global/common/constants/FcmNotificationConstants.java
src/main/java/com/depromeet/stonebed/scheduler/fcm/FcmScheduler.java
src/test/java/com/depromeet/stonebed/domain/fcm/application/FcmSchedulerTest.java

fix: 푸시 알림 메세지 조건 수정

---

src/main/java/com/depromeet/stonebed/domain/feed/api/FeedController.java
src/main/java/com/depromeet/stonebed/domain/feed/application/FeedService.java
src/main/java/com/depromeet/stonebed/domain/feed/dao/FeedRepositoryCustom.java
src/main/java/com/depromeet/stonebed/domain/feed/dao/FeedRepositoryImpl.java
src/main/java/com/depromeet/stonebed/global/error/ErrorCode.java
src/test/java/com/depromeet/stonebed/domain/feed/application/FeedServiceTest.java

- close #299 
- 단일 피드 조회 API 뚫기~
- RepositoryImpl 구현체 클래스도 분리하였습니도
-
-

feat: 단일 피드 조회 API

---

src/main/java/com/depromeet/stonebed/domain/discord/application/DiscordNotificationService.java
src/main/java/com/depromeet/stonebed/domain/fcm/application/FcmNotificationService.java

- close #301 
- 알림 리스트에서 filter 함수 제거
-
-

fix: 알림 리스트 필터 제거

---

src/main/java/com/depromeet/stonebed/domain/feed/api/FeedController.java
src/main/java/com/depromeet/stonebed/domain/feed/application/FeedService.java
src/main/java/com/depromeet/stonebed/domain/feed/dto/response/v1/FeedContentGetResponse.java
src/main/java/com/depromeet/stonebed/domain/feed/dto/response/v1/FeedGetResponse.java
src/main/java/com/depromeet/stonebed/domain/feed/dto/response/v2/FeedContentGetResponseV2.java
src/main/java/com/depromeet/stonebed/domain/feed/dto/response/v2/FeedGetResponseV2.java
src/test/java/com/depromeet/stonebed/domain/feed/application/FeedServiceTest.java

- close #303 
- 피드 v2 엔드포인트, 모델 추가
-
-

feat: v2 엔드 포인트 및 모델 추가

---

src/main/java/com/depromeet/stonebed/domain/comment/application/CommentService.java
src/main/java/com/depromeet/stonebed/domain/fcm/application/FcmNotificationService.java
src/main/java/com/depromeet/stonebed/domain/fcm/domain/FcmNotification.java
src/main/java/com/depromeet/stonebed/scheduler/fcm/FcmScheduler.java
src/test/java/com/depromeet/stonebed/domain/fcm/application/FcmNotificationServiceTest.java
src/test/java/com/depromeet/stonebed/domain/fcm/application/FcmSchedulerTest.java

- close #305 
- 딥링크 로직 개선
- 불필요한 sendBoostNotification 메서드 제거
- 댓글 딥링크 내용 수정
-
-

refactor: 딥링크 수정

---

src/main/java/com/depromeet/stonebed/domain/missionRecord/api/MissionRecordController.java

test: fcmScheduler테스트

---

src/main/java/com/depromeet/stonebed/domain/missionRecord/api/MissionRecordController.java
src/main/java/com/depromeet/stonebed/domain/sqs/application/SqsMessageService.java
src/test/java/com/depromeet/stonebed/domain/missionRecord/api/MissionRecordControllerTest.java

- close #311 
- Fcm 스케쥴러 BatchEntry ID 값 UUID로 수정
-
-

Fcm 스케쥴러 BatchEntry ID 값 UUID로 수정

---

src/main/java/com/depromeet/stonebed/domain/comment/dto/request/CommentCreateRequest.java
src/test/java/com/depromeet/stonebed/domain/comment/application/CommentServiceTest.java

- close #296 
- 댓글 생성에 대한 테스트 코드로 기본적으로 부모, 자식 댓글에 대한 생성 테스트 코드 작성
- recordId를 통해 댓글 조회를 하며, 댓글 내용, 댓글 수 체킹
-
-

test: 댓글 테스트 코드

---

src/main/java/com/depromeet/stonebed/domain/auth/application/AuthService.java
src/main/java/com/depromeet/stonebed/domain/report/api/ReportController.java
src/main/java/com/depromeet/stonebed/domain/report/application/ReportService.java
src/main/java/com/depromeet/stonebed/domain/report/dao/ReportRepository.java
src/main/java/com/depromeet/stonebed/domain/report/domain/Report.java
src/main/java/com/depromeet/stonebed/domain/report/domain/ReportDomain.java
src/main/java/com/depromeet/stonebed/domain/report/dto/request/ReportCreateRequest.java
src/test/java/com/depromeet/stonebed/domain/auth/application/AuthServiceTest.java

- close #319 
- 특정 연관관계(mission_record)에 따른 설계가 아닌 report에 대해 다른 확장성 고려
- targetId로 명칭
-
-

refactor: 신고 엔티티 구조 변경

---

src/main/java/com/depromeet/stonebed/domain/fcm/application/FcmNotificationService.java
src/main/java/com/depromeet/stonebed/domain/fcm/dao/FcmNotificationRepository.java
src/main/java/com/depromeet/stonebed/domain/fcm/dao/FcmNotificationRepositoryCustom.java
src/main/java/com/depromeet/stonebed/domain/fcm/dao/FcmNotificationRepositoryImpl.java

- close #324 
- 알림 페이지, 기록에 대한 예외 처리
- Querydsl로 리팩토링
-
-

fix: 알림 페이지, 기록에 대한 예외 처리

---

src/main/java/com/depromeet/stonebed/domain/fcm/application/FcmNotificationService.java
src/main/java/com/depromeet/stonebed/domain/fcm/dao/FcmNotificationRepositoryImpl.java
src/test/java/com/depromeet/stonebed/domain/fcm/application/FcmNotificationServiceTest.java

- close #324 
- where 조건과 join on 처리 수정
-
-

fix: 알림 리스트 페이지 where 조건 처리
