- .github/workflows/develop-pull-request-on-check.yml
- close #4 
- Pull Request 생성 시 gradle Check 실행
- 워크플로에서 추가해야 하거나 수정해야하는 부분 있다면 피드백 부탁드릴게요:)
- [gradle-build-action](https://github.com/gradle/gradle-build-action)
- [build-action 적용 블로그](https://velog.io/@sontulip/github-actions-ci#gradlegradle-build-action%EC%9D%84-%EC%9D%B4%EC%9A%A9%ED%95%98%EA%B8%B0)
- https://www.baeldung.com/gradle-test-vs-check
> chore: develop PR on check workflow 작성

- build.gradle
- src/main/resources/application.yml
- close #3 
- Spring Actuator 구성
- `/walwal-actuator/health`로 health 체크
- 액추에이터 관련 보안 설정을 적용
- jmx 방식은 모든 endpoint를 사용하므로 비활성화
- health 관련 엔드포인트만 활성화
- `application.yml`에 옵션까지 작업 내용에 설명하였습니다!
- https://techblog.woowahan.com/9232/
> chore: Spring Actuator 구성

- build.gradle
- src/main/java/com/depromeet/stonebed/global/config/SwaggerConfig.java
- src/main/resources/application.yml
- close #13 
- Springdoc + Swagger 프로젝트 기본 설정
- Springdoc-openapi-v2.3.0
- springfox 라이브러리 업데이트 종료로 인해 SpringBoot 3.x.x버전에서 사용에 용이한 Springdoc-openapi-v2 이상 사용권장. 
- 아직 API 문서 인증(Authroize) 기능은 설정하지 않았습니다. 추후에 Security 설정하고 JWT토큰을 통한 인증과정 추가하겠습니다.
- https://blog.naver.com/seek316/223349824088
- https://wonsjung.tistory.com/584
> [WALWAL-96] SwaggerConfig 작성

- build.gradle
- close #6
- Code Coverage Dependancy 추가
- `test` 작업 이후 실행되도록 설정
- 메인 Application, test 파일들은 카운팅에서 제외
- 추가로 필터링하면 좋을 옵션들을 알려주시면 좋을 것 같아요.
- 사소한 변수명이나 Coverage reports의 저장 경로같은 경우도 의견을 듣고 싶어요
- [jacoco - Mission](https://www.jacoco.org/jacoco/trunk/doc/mission.html)
- [gradle - JacocoReport](https://docs.gradle.org/current/dsl/org.gradle.testing.jacoco.tasks.JacocoReport.html)
- [gradle - JacocoCoverageVerification](https://docs.gradle.org/current/dsl/org.gradle.testing.jacoco.tasks.JacocoCoverageVerification.html)
- [우아한 기술블로그 - Gradle 프로젝트에 JaCoCo 설정하기](https://techblog.woowahan.com/2661/)
- [윤범님 블로그 - [Spring boot] Jacoco + Sonarcloud 로 코드 커버리지 분석하기](https://velog.io/@uiurihappy/Spring-Jacoco-Sonarcloud-%EB%A1%9C-%EC%BD%94%EB%93%9C-%EB%B6%84%EC%84%9D%ED%95%98%EA%B8%B0)
> [WALWAL-84] jacoco 세팅 추가

- src/main/java/com/depromeet/stonebed/domain/common/BaseTimeEntity.java
- src/main/java/com/depromeet/stonebed/global/config/jpa/JpaConfig.java
- close #21 
- BaseTimeEntity 추가로 createdAt과 updatedAt을 상속받아 Entity 구성할 수 있도록 구현
- EnableJpaAuditing는 별도의 config로 분리하여 관리
-
-
> [WALWAL-107] BaseTimeEntity 추가

- .gitignore
- build.gradle
- src/main/java/com/depromeet/stonebed/domain/common/BaseTimeEntity.java
- src/main/resources/application.yml
- src/test/java/com/depromeet/stonebed/fixtureMonkeyTest/Order.java
- src/test/java/com/depromeet/stonebed/fixtureMonkeyTest/TestFixtureMonkey.java
- src/test/java/com/depromeet/stonebed/fixtureMonkeyTest/User.java
- src/test/resources/application-test.yml
- close #18 
- fixtureMonkey 도입
- 테스트 `@Data` 클래스를 생성하여 진행
- fixtureMonkey 객체 생성 시 파라미터 set을 해야 한다.
-
- [올리브영 fixtureMonkey 도입기](https://oliveyoung.tech/blog/2024-04-01/testcode-use-fixture-monkey/)
- [deview 레퍼런스](https://deview.kr/data/deview/session/attach/11_%ED%85%8C%EC%8A%A4%ED%8A%B8%20%EA%B0%9D%EC%B2%B4%EB%8A%94%20%EC%97%A3%EC%A7%80%20%EC%BC%80%EC%9D%B4%EC%8A%A4%EA%B9%8C%EC%A7%80%20%EC%B0%BE%EC%95%84%EC%A3%BC%EB%8A%94%20Fixture%20Monkey%EC%97%90%EA%B2%8C%20%EB%A7%A1%EA%B8%B0%EC%84%B8%EC%9A%94.pdf)
- [랜덤 데이터 생성 라이브러리](https://velog.io/@phdljr/TIL-FixtureMonkey-%EB%9E%9C%EB%8D%A4-%EB%8D%B0%EC%9D%B4%ED%84%B0-%EC%83%9D%EC%84%B1-%EB%9D%BC%EC%9D%B4%EB%B8%8C%EB%9F%AC%EB%A6%AC)
> [WALWAL-106] fixtureMonkey 도입

- .github/workflows/develop-build-deploy.yml
- docker-compose.yaml
- src/main/java/com/depromeet/stonebed/global/annotation/ConditionalOnProfile.java
- src/main/java/com/depromeet/stonebed/global/annotation/OnProfileCondition.java
- src/main/java/com/depromeet/stonebed/global/common/constants/EnvironmentConstants.java
- src/main/java/com/depromeet/stonebed/global/config/security/WebSecurityConfig.java
- src/main/java/com/depromeet/stonebed/global/config/swagger/SwaggerConfig.java
- src/main/java/com/depromeet/stonebed/global/util/CookieUtil.java
- src/main/java/com/depromeet/stonebed/global/util/SpringEnvironmentUtil.java
- src/main/resources/application-dev.yml
- src/test/java/com/depromeet/stonebed/fixtureMonkeyTest/TestFixtureMonkey.java
- src/test/java/com/depromeet/stonebed/global/util/SpringEnvironmentUtilTest.java
- close #54 
- dev와 prod Profile에 대한 환경분리를 진행
- SwaggerConfig, SecurityConfig 등 필요한 영역에 환경분리를 진행
- 잠수함 패치가 몇개 있습니당
- EC2 내부 환경 변수 및 EB 환경 변수로 SPRING_PROFILES_ACTIVE 변수를 추가
- 
-
> [WALWAL-148] Dev, Prod 환경 분리

- src/main/java/com/depromeet/stonebed/domain/mission/api/MissionController.java
- src/main/java/com/depromeet/stonebed/domain/mission/application/MissionService.java
- src/main/java/com/depromeet/stonebed/domain/mission/dao/MissionHistoryRepository.java
- src/main/java/com/depromeet/stonebed/domain/mission/dao/MissionRepository.java
- src/main/java/com/depromeet/stonebed/domain/mission/dao/MissionRepositoryCustom.java
- src/main/java/com/depromeet/stonebed/domain/mission/dao/MissionRepositoryImpl.java
- src/main/java/com/depromeet/stonebed/domain/mission/domain/MissionHistory.java
- src/main/java/com/depromeet/stonebed/domain/mission/dto/response/MissionGetTodayResponse.java
- src/main/java/com/depromeet/stonebed/global/error/ErrorCode.java
- src/test/java/com/depromeet/stonebed/domain/mission/api/MissionControllerTest.java
- src/test/java/com/depromeet/stonebed/domain/mission/application/MissionServiceTest.java
- src/test/java/com/depromeet/stonebed/domain/mission/dao/MissionHistoryRepositoryTest.java
- src/test/java/com/depromeet/stonebed/domain/mission/dao/MissionRepositoryTest.java
- close #51 
- GET /missions/today 엔드포인트 추가
- 3일 내에 할당된 미션은 다시 할당되지 않음
- 로직을 테스트에 적용했더니 꽤 복잡해서 주석을 많이 사용했어요
- 전에 말씀해주셨던 publishedAt 보다 date같아서 At 말고 Date 를 사용했고, publish는 뭔가 발행일 같아서 할당된 날짜...? 같은 느낌으로 assignedDate로 지어봤어요
- 테스트에 fixture monkey는 ... 사진 업로드까지만 하고 지금까지 작업한거 리팩토링 해보겠습니당...
- Secure Random 보안 경고 ([Link](https://github.com/depromeet/WalWal-server/pull/53#issue-2422751877))
- [자바의 난수생성기 Random, SecureRandom](https://velog.io/@dudwls0505/%EC%9E%90%EB%B0%94%EC%9D%98-%EB%82%9C%EC%88%98%EC%83%9D%EC%84%B1%EA%B8%B0-Random-SecureRandom)
- [[Java] Random보단 SecureRandom 를 사용하자.](https://kdhyo98.tistory.com/48#google_vignette)
> [WALWAL-147] 오늘의 미션 API 추가

- docker-compose.yaml
- close #76 
- 도커 컴포즈 메모리 제한
- 배포 환경 t3.micro 메모리 1기가에서 원활하게 애플리케이션이 동작하도록 메모리를 제한합니다
- Springboot: 640 (512 + 128) MB
- Redis: 128 MB
- Nginx: 128 MB
- 인스턴스에서 128 정도는 여유있게 할당해봤어요
-
> [WALWAL-163] 배포 환경 메모리 제한

- src/main/java/com/depromeet/stonebed/domain/mission/dao/MissionHistoryRepository.java
- src/main/java/com/depromeet/stonebed/domain/mission/dao/MissionHistoryRepositoryCustom.java
- src/main/java/com/depromeet/stonebed/domain/mission/dao/MissionHistoryRepositoryImpl.java
- src/main/java/com/depromeet/stonebed/domain/missionRecord/application/MissionRecordService.java
- src/main/java/com/depromeet/stonebed/domain/missionRecord/dao/MissionRecordRepository.java
- src/main/java/com/depromeet/stonebed/domain/missionRecord/domain/MissionRecord.java
- src/main/java/com/depromeet/stonebed/global/error/ErrorCode.java
- src/test/java/com/depromeet/stonebed/domain/missionRecord/MissionRecordServiceTest.java
- close #72 
- 기존 mission:missionRecord 1:N 관계에서 missionHistory:missionRecord 1:N 관계로 변경
- 문제는 missionRecord의 중복 생성인데, assignedDate, member_id, mission 이렇게 3개가 고유 제약 조건이어야 한다
- 하지만 mission은 날짜를 구분하는 assignedDate가 없기 때문에 missionHistroy로 관계를 변경
- 그리고 기존 missionRecord 관련 서비스에서 mission 으로 찾고, mission을 넣어주는 과정을 전부 missionHistory로 변경
- unique key 네이밍이나 querydsl 네이밍에서 더 좋은 이름이 있다면 추천을 해주세용
-
> [WALWAL-160] 미션 시작 시 동시성 문제 개선

- src/main/java/com/depromeet/stonebed/domain/mission/domain/Mission.java
- src/main/java/com/depromeet/stonebed/domain/mission/dto/response/MissionGetTodayResponse.java
- src/main/java/com/depromeet/stonebed/domain/missionRecord/api/MissionRecordController.java
- src/test/java/com/depromeet/stonebed/domain/mission/api/MissionControllerTest.java
- close #89 
- Mission Response에서 HexColor값 제거
- MissionRecord saveMission메서드에 PostMapping {/missionId}추가
-
-
> [WALWAL-167] Mission Response 및 API PathVariable 수정

- src/test/java/com/depromeet/stonebed/FixtureMonkeySetUp.java
- src/test/java/com/depromeet/stonebed/domain/auth/application/AuthServiceTest.java
- src/test/java/com/depromeet/stonebed/domain/auth/application/JwtTokenServiceTest.java
- src/test/java/com/depromeet/stonebed/domain/feed/application/FeedServiceTest.java
- src/test/java/com/depromeet/stonebed/domain/follow/application/FollowServiceTest.java
- src/test/java/com/depromeet/stonebed/domain/member/application/MemberServiceTest.java
- src/test/java/com/depromeet/stonebed/domain/member/domain/MemberTest.java
- src/test/java/com/depromeet/stonebed/domain/mission/api/MissionControllerTest.java
- src/test/java/com/depromeet/stonebed/domain/mission/application/MissionServiceTest.java
- src/test/java/com/depromeet/stonebed/domain/mission/dao/MissionHistoryRepositoryTest.java
- src/test/java/com/depromeet/stonebed/domain/mission/dao/MissionRepositoryTest.java
- src/test/java/com/depromeet/stonebed/domain/missionRecord/MissionRecordServiceTest.java
- src/test/java/com/depromeet/stonebed/global/util/MemberUtilTest.java
- src/test/java/com/depromeet/stonebed/global/util/SecurityUtilTest.java
- src/test/java/com/depromeet/stonebed/global/util/SpringEnvironmentUtilTest.java
- close #105 
- 공통으로 사용된 setUp 함수 내부 중 fixtureMonkey 사용이 중복적으로 사용되는 것을 추상 클래스를 사용해 상속으로 개선
- 잠수함 패치로 `@ActiveProfiles("test")`를 추가하여 H2 데이터베이스를 사용하게 하여 테스트 실행시간 4~5초에서 2~3초로 개선
-
> refactor: fixtureMonkey setUp 함수 추상 클래스로 상속으로 개선

- src/main/java/com/depromeet/stonebed/domain/missionRecord/api/MissionRecordController.java
- src/main/java/com/depromeet/stonebed/domain/missionRecord/application/MissionRecordService.java
- src/main/java/com/depromeet/stonebed/domain/missionRecord/dto/request/MissionRecordCalendarRequest.java
- src/main/java/com/depromeet/stonebed/domain/missionRecord/dto/response/MissionRecordCalendarResponse.java
- src/test/java/com/depromeet/stonebed/domain/missionRecord/MissionRecordServiceTest.java
- close #129 
- 캘린더 뷰 조회 방식을 POST -> GET으로 변경
- Request Body가 아닌 QueryString으로 RequestParam을 사용
- 다른 사용자의 캘린더 뷰를 조회할 수 있도록 memberId 인자 추가
-
-
> refactor: 다른 유저 캘린더 조회 및 GET 요청으로 변경

- src/main/java/com/depromeet/stonebed/domain/feed/api/FeedController.java
- src/main/java/com/depromeet/stonebed/domain/feed/application/FeedService.java
- src/main/java/com/depromeet/stonebed/domain/feed/dto/response/FeedContentGetResponse.java
- src/main/java/com/depromeet/stonebed/domain/missionRecord/api/MissionRecordController.java
- src/main/java/com/depromeet/stonebed/domain/missionRecord/application/MissionRecordService.java
- src/main/java/com/depromeet/stonebed/domain/missionRecord/domain/MissionRecord.java
- src/main/java/com/depromeet/stonebed/domain/missionRecord/dto/request/MissionRecordBoostRequest.java
- src/test/java/com/depromeet/stonebed/domain/feed/application/FeedServiceTest.java
- src/test/java/com/depromeet/stonebed/domain/missionRecord/api/MissionRecordControllerTest.java
- src/test/java/com/depromeet/stonebed/domain/missionRecord/application/MissionRecordServiceTest.java
- close #136 
- 부스트 엔드포인트 변경
- `/feed/boost` -> `/records/<missionRecordId>/boost`
- 피드 API에 content 추가
- 미션 기록 모델에 `text` 필드 삭제 
- 미션 기록 모델에 `content` 필드 추가
-
-
> feature: 부스트 위치 변경 및 피드 컨텐츠 추가

- src/main/java/com/depromeet/stonebed/domain/fcm/api/FcmController.java
- src/main/java/com/depromeet/stonebed/domain/fcm/application/FcmService.java
- src/main/java/com/depromeet/stonebed/domain/fcm/application/FcmTokenService.java
- close #145 
- FCM 토큰 삭제 시 request제거
- invalidateToken메서드, invalidateTokenForCurrentMember메서드로 분리
-
-
> fix: invalidateTokenForCurrentMember메서드 추가 및 수정

- src/main/java/com/depromeet/stonebed/domain/mission/application/MissionService.java
- src/main/java/com/depromeet/stonebed/domain/mission/dao/mission/MissionRepositoryCustom.java
- src/main/java/com/depromeet/stonebed/domain/mission/dao/mission/MissionRepositoryImpl.java
- src/main/java/com/depromeet/stonebed/domain/mission/domain/MissionHistory.java
- src/test/java/com/depromeet/stonebed/domain/mission/application/MissionServiceTest.java
- src/test/java/com/depromeet/stonebed/domain/mission/dao/MissionHistoryRepositoryTest.java
- close #148 
- 오늘의 미션 할당 로직 중 before가 아닌 after로 수정
- `mh1_0.assigned_date> 3일전 LocalDate`로 수정하여 NotIn 처리하도록 수정 
-
-
> hotfix: today API before -> after 수정

- src/main/java/com/depromeet/stonebed/domain/fcm/api/FcmController.java
- src/main/java/com/depromeet/stonebed/domain/fcm/application/FcmNotificationService.java
- src/main/java/com/depromeet/stonebed/domain/fcm/application/FcmScheduledService.java
- src/main/java/com/depromeet/stonebed/domain/fcm/application/FcmService.java
- src/main/java/com/depromeet/stonebed/domain/fcm/dao/FcmNotificationRepository.java
- src/main/java/com/depromeet/stonebed/domain/fcm/domain/FcmNotification.java
- src/main/java/com/depromeet/stonebed/domain/fcm/domain/FcmNotificationType.java
- src/main/java/com/depromeet/stonebed/domain/fcm/dto/response/FcmNotificationDto.java
- src/main/java/com/depromeet/stonebed/domain/fcm/dto/response/FcmNotificationResponse.java
- src/main/java/com/depromeet/stonebed/domain/missionRecord/api/MissionRecordController.java
- src/main/java/com/depromeet/stonebed/domain/missionRecord/application/MissionRecordService.java
- src/main/java/com/depromeet/stonebed/domain/missionRecord/dao/MissionRecordBoostRepository.java
- src/main/java/com/depromeet/stonebed/domain/missionRecord/dao/MissionRecordRepository.java
- src/main/java/com/depromeet/stonebed/global/common/constants/FcmNotificationConstants.java
- src/main/java/com/depromeet/stonebed/global/error/ErrorCode.java
- src/test/java/com/depromeet/stonebed/StonebedApplicationTests.java
- src/test/java/com/depromeet/stonebed/domain/fcm/application/FcmNotificationServiceTest.java
- src/test/java/com/depromeet/stonebed/domain/fcm/application/FcmScheduledServiceTest.java
- src/test/java/com/depromeet/stonebed/domain/missionRecord/application/MissionRecordServiceTest.java
- src/test/java/com/depromeet/stonebed/fixtureMonkeyTest/TestFixtureMonkey.java
- close #135 
- 스케쥴러 알림 메세지 전송시 FcmNotification에 저장
- /alarm API 호출 시 알림 리스트 조회
- /{notificationId}/read API 호출 시 알림 읽음 처리
- 알림 리스트 조회 시 아래의 형식으로 조회되는데 수정사항이나 개선사항있으면 말씀 부탁드려용!
참고로 targetId는 일반 MISSION화면으로 돌아가는 MISSION type의경우 null로 보내고있고, BOOSTER type의경우 해당 피드로돌아가는 recordId를 포함하고있습니다.
```
{
"success": true,
"status": 200,
"data": [
{
"notificationId": 1,
"type": "MISSION",
"title": "정규 메세지 제목",
"message": "정규 메세지 내용",
"imageUrl": null,
"isRead": true,
"targetId": null,
"createdAt": "2024-08-17T11:46:30.376179"
},
{
"notificationId": 4,
"type": "BOOSTER",
"title": "인기쟁이",
"message": "게시물 부스터를 500개를 달성했어요!",
"imageUrl": null,
"isRead": false,
"targetId": 4,
"createdAt": "2024-08-17T13:42:07.660621"
}
]
}
```
-
> [WALWAL-173] fcm alarm list 구현 

- src/main/java/com/depromeet/stonebed/domain/mission/api/MissionController.java
- src/main/java/com/depromeet/stonebed/domain/mission/application/MissionService.java
- src/main/java/com/depromeet/stonebed/domain/mission/dao/mission/MissionRepositoryCustom.java
- src/main/java/com/depromeet/stonebed/domain/mission/dao/mission/MissionRepositoryImpl.java
- src/main/java/com/depromeet/stonebed/domain/mission/dao/missionHistory/MissionHistoryRepository.java
- src/main/java/com/depromeet/stonebed/domain/mission/dao/missionHistory/MissionHistoryRepositoryCustom.java
- src/main/java/com/depromeet/stonebed/domain/mission/dao/missionHistory/MissionHistoryRepositoryImpl.java
- src/main/java/com/depromeet/stonebed/domain/mission/domain/Mission.java
- src/main/java/com/depromeet/stonebed/domain/mission/domain/MissionHistory.java
- src/main/java/com/depromeet/stonebed/domain/mission/dto/request/MissionCreateRequest.java
- src/main/java/com/depromeet/stonebed/domain/mission/dto/request/MissionUpdateRequest.java
- src/test/java/com/depromeet/stonebed/domain/mission/api/MissionControllerTest.java
- src/test/java/com/depromeet/stonebed/domain/mission/application/MissionServiceTest.java
- src/test/java/com/depromeet/stonebed/domain/mission/dao/MissionHistoryRepositoryTest.java
- src/test/java/com/depromeet/stonebed/domain/mission/dao/MissionRepositoryTest.java
- close #167 
- 미션별 강아지/고양이 분류
- 본인이 선택한 반려동물에 따라서 /today미션제공
- 하루에 강아지/고양이 1개씩 들어가야하므로 기존 unique값인 assigned_date를 제거하고, assigned_date + mission_id조합으로 uniqueConstraints을 걸어서 관리하도록 했습니다.
- 제가 요구사항에 맞게 구현한건지 피드백 부탁드립니다!
-
> [WALWAL-174] raisepet mission supply

- src/main/java/com/depromeet/stonebed/domain/auth/application/AuthService.java
- src/main/java/com/depromeet/stonebed/domain/common/BaseFullTimeEntity.java
- src/main/java/com/depromeet/stonebed/domain/fcm/dao/FcmNotificationRepository.java
- src/main/java/com/depromeet/stonebed/domain/fcm/domain/FcmNotification.java
- src/main/java/com/depromeet/stonebed/domain/fcm/domain/FcmToken.java
- src/main/java/com/depromeet/stonebed/domain/member/domain/Member.java
- src/main/java/com/depromeet/stonebed/domain/missionRecord/dao/MissionRecordBoostRepository.java
- src/main/java/com/depromeet/stonebed/domain/missionRecord/dao/MissionRecordRepository.java
- src/main/java/com/depromeet/stonebed/domain/missionRecord/domain/MissionRecord.java
- src/main/java/com/depromeet/stonebed/domain/missionRecord/domain/MissionRecordBoost.java
- src/main/java/com/depromeet/stonebed/global/util/MemberUtil.java
- src/test/java/com/depromeet/stonebed/domain/auth/application/AuthServiceTest.java
- close #164 
- 회원 탈퇴 시 deleteById로 delete 이벤트 발생 시 cascade에 따른 데이터 삭제
- cascade 삭제를 시도했으나 row마다 쿼리가 발생되는 이슈로 native 쿼리 방식 활용
- soft-delete 처리 시 언제 삭제를 진행했는지 트래킹 활용 목적으로 deletedAt을 추가
- Profile 데이터 초기화
- 테스트 코드 수정
- 잠수함 패치로 MemberUtil 코드 Transactional 어노테이션 추가
- boost엔티티 member 정보 null 허용
- Lazy 로딩 추가
-
> fix: 회원탈퇴 데이터 초기화

- src/main/java/com/depromeet/stonebed/domain/mission/application/MissionService.java
- src/main/java/com/depromeet/stonebed/domain/mission/domain/MissionHistory.java
- src/test/java/com/depromeet/stonebed/domain/mission/application/MissionServiceTest.java
- src/test/java/com/depromeet/stonebed/domain/mission/dao/MissionHistoryRepositoryTest.java
- close #175 
- missionHistory에 raisePet 값 추가
- unique 제약 조건을 missionId -> raisePet으로 변경
-
-
> fix: today 미션 raisePet에 따라 미션 할당

- src/main/java/com/depromeet/stonebed/domain/feed/api/FeedController.java
- src/main/java/com/depromeet/stonebed/domain/feed/application/FeedService.java
- src/main/java/com/depromeet/stonebed/domain/feed/dao/FeedRepositoryCustom.java
- src/main/java/com/depromeet/stonebed/domain/feed/dao/FeedRepositoryImpl.java
- src/main/java/com/depromeet/stonebed/domain/feed/dto/request/FeedGetRequest.java
- src/test/java/com/depromeet/stonebed/domain/feed/application/FeedServiceTest.java
- close #178 
- 피드의 다음 데이터가 없는 경우 nextCursor=null 처리
- 미션기록이 `COMPLETED` 인 데이터만 가져오도록 수정
- 한 멤버만 필터링할 수 있도록 `@RequestParam(required = false) Long memberId` 추가
-
-
> fix: 피드 nextCursor=null 처리 및 미션기록 상태 완료만 나오도록 처리 & 멤버 파라메터 추가

- src/main/java/com/depromeet/stonebed/domain/feed/dao/FeedRepositoryImpl.java
- close #183 
- 피드 하나 조회할 때 `fetchOne` -> `fetchFirst` 로 수정
- fetchOne은 1개임을 보장하지 않는 걸 몰랐음... ㅜ
-
-
> fix: 피드 조회 `fetchOne` -> `fetchFirst` 로수정

- src/main/java/com/depromeet/stonebed/domain/fcm/dao/FcmRepository.java
- src/main/java/com/depromeet/stonebed/domain/fcm/dao/FcmRepositoryCustom.java
- src/main/java/com/depromeet/stonebed/domain/fcm/dao/FcmRepositoryImpl.java
- close #192 
- 기존 JPQL쿼리에서 확장성을 생각해 QueryDSL로 바꿨고, 조건에 token is not null 추가
-
-
> Fcm 알림 메세지 전송 시 token is not null 조건 추가

- src/main/java/com/depromeet/stonebed/domain/missionRecord/api/MissionRecordController.java
- src/main/java/com/depromeet/stonebed/domain/missionRecord/application/MissionRecordService.java
- src/main/java/com/depromeet/stonebed/domain/missionRecord/dao/MissionRecordRepository.java
- src/main/java/com/depromeet/stonebed/domain/missionRecord/dao/MissionRecordRepositoryImpl.java
- src/main/java/com/depromeet/stonebed/domain/missionRecord/dto/request/MissionRecordCalendarRequest.java
- src/main/java/com/depromeet/stonebed/global/error/ErrorCode.java
- src/test/java/com/depromeet/stonebed/domain/missionRecord/application/MissionRecordServiceTest.java
- close #229 
- 미션이 COMPLETED인 상태 기록만 불러오는 조건 추가
- 컨트롤러 파라미터 컨벤션 조정
- 같은 날 여러개의 데이터가 존재하는 엣지케이스 방지 위해 미션 기록 저장 시 방어 로직 추가
- 같은 날 여러개의 데이터가 존재할 때 최근꺼를 가져오는 것 보다, 처음부터 미션 기록이 저장 될 때 같은 날 2개 이상의 데이터가 저장되지 않게 막아놨습니다.
-
> 미션 기록 캘린더 중복 로직 수정

- src/main/java/com/depromeet/stonebed/domain/missionRecord/application/MissionRecordService.java
- src/main/java/com/depromeet/stonebed/domain/missionRecord/dao/MissionRecordRepository.java
- close #232 
- 현재 COMPLETED가 아닌 상태에도 미션 기록 중복 저장 에러 발생하고있어서 COMPLETED일 때만 안되게 수정
-
-
> 미션 기록 캘린더 COMPLETED인 데이터만 조회

- src/main/java/com/depromeet/stonebed/domain/auth/application/AuthService.java
- src/main/java/com/depromeet/stonebed/domain/fcm/dao/FcmNotificationRepository.java
- src/main/java/com/depromeet/stonebed/domain/fcm/domain/FcmNotification.java
- src/main/java/com/depromeet/stonebed/domain/member/dao/MemberRepository.java
- src/main/java/com/depromeet/stonebed/domain/member/domain/Member.java
- src/main/java/com/depromeet/stonebed/domain/missionRecord/dao/MissionRecordBoostRepository.java
- src/main/java/com/depromeet/stonebed/domain/missionRecord/dao/MissionRecordRepository.java
- src/main/java/com/depromeet/stonebed/domain/missionRecord/domain/MissionRecord.java
- src/main/java/com/depromeet/stonebed/domain/missionRecord/domain/MissionRecordBoost.java
- src/test/java/com/depromeet/stonebed/domain/auth/application/AuthServiceTest.java
- close #239 
- 내부 의논을 통해 Soft -> Hard Delete로 변경
-
-
> fix: 회원탈퇴 데이터 삭제 방식 변경

- src/main/java/com/depromeet/stonebed/domain/fcm/application/FcmNotificationService.java
- src/main/java/com/depromeet/stonebed/domain/fcm/domain/FcmMessage.java
- src/main/java/com/depromeet/stonebed/domain/fcm/domain/FcmNotification.java
- src/main/java/com/depromeet/stonebed/domain/fcm/dto/response/FcmNotificationDto.java
- src/main/java/com/depromeet/stonebed/domain/sqs/application/SqsMessageService.java
- close #256 
- 기존에는 dto를 통해 deepLink를 제공해서 이동되어야하는 줄 알았는데, dto에서 제거하고 FcmMessage에 포함시켜 푸시알림에서 해당 게시글로 이동되게 수정
-
-
> Fcm 메세지에 deepLink 페이로드 설정

- src/main/java/com/depromeet/stonebed/domain/feed/dao/FeedRepositoryImpl.java
- src/main/java/com/depromeet/stonebed/domain/missionRecord/application/MissionRecordService.java
- src/main/java/com/depromeet/stonebed/domain/missionRecord/dto/response/MissionTabResponse.java
- src/test/java/com/depromeet/stonebed/domain/missionRecord/application/MissionRecordServiceTest.java
- close #254 
- 미션 완료에 대한 Response 필드 추가
- 필드 추가 사항
- 미션 명
- 미션 일러스트 이미지 url
- 미션 기록 내용
- 미션 완료 일자(LocalDate)
- 잠수함 패치로 피드에 대한 정렬을 updatedAt 기준으로 변경
-
> feat: 미션 완료 카드 Response 필드 추가

- src/main/java/com/depromeet/stonebed/domain/fcm/application/FcmNotificationService.java
> fix: token not found throw 하지 않도록 수정

- src/main/java/com/depromeet/stonebed/domain/fcm/application/FcmNotificationService.java
- src/main/java/com/depromeet/stonebed/domain/fcm/dao/FcmTokenRepository.java
- src/main/java/com/depromeet/stonebed/domain/sqs/application/SqsMessageService.java
- close #274 
- FCM 관련해서 앱을 삭제하거나, FCM토큰이 만료된경우 토큰 삭제하는 로직 추가
-
-
> FCM 푸시 알림, 유효하지 않은 FCM토큰 삭제

- src/main/java/com/depromeet/stonebed/scheduler/fcm/FcmScheduler.java
- close #277 
- FCM 메세지 저장시 null값 중복으로 인해 에러발생, token값 null인것 대상에서 제외
-
-
> FCM 메세지 저장시 null값 중복으로 인해 에러발생, token값 null인것 대상에서 제외

- src/main/java/com/depromeet/stonebed/domain/comment/application/CommentService.java
- src/main/java/com/depromeet/stonebed/domain/fcm/application/FcmNotificationService.java
- src/main/java/com/depromeet/stonebed/domain/fcm/domain/FcmNotificationType.java
- src/main/java/com/depromeet/stonebed/global/common/constants/FcmNotificationConstants.java
- src/main/java/com/depromeet/stonebed/scheduler/fcm/FcmScheduler.java
- src/test/java/com/depromeet/stonebed/domain/fcm/application/FcmSchedulerTest.java
- close #288 
- 댓글 생성 시 작성자에게 알림
- 대댓글 작성 시 부모 댓글 사용자, 기록 작성자에게 푸시 알림
- 기존 sendNotification에 FcmNotificationType도 인자를 받도록 재사용성 개선
- 댓글 푸시 알림은 추후 디쟌팀에게 전달받아 수정할 예정
-
> feat: 댓글 생성 시 푸시 알림

- src/main/java/com/depromeet/stonebed/domain/fcm/application/FcmNotificationService.java
- src/main/java/com/depromeet/stonebed/domain/sqs/application/SqsMessageService.java
- src/main/java/com/depromeet/stonebed/global/common/constants/NotificationConstants.java
- close #313 
- 알림 변수는 별도 분리
- sqs service 코드 메서드 분리
-
-
> refactor: 알림 변수 상수화 및 메서드 분리

- src/main/java/com/depromeet/stonebed/domain/auth/application/AuthService.java
- src/main/java/com/depromeet/stonebed/domain/comment/application/CommentService.java
- src/main/java/com/depromeet/stonebed/domain/comment/dao/CommentRepositoryCustom.java
- src/main/java/com/depromeet/stonebed/domain/comment/dao/CommentRepositoryImpl.java
- src/main/java/com/depromeet/stonebed/domain/comment/domain/Comment.java
- src/main/java/com/depromeet/stonebed/domain/feed/application/FeedService.java
- src/main/java/com/depromeet/stonebed/domain/feed/dao/FeedRepositoryImpl.java
- src/main/java/com/depromeet/stonebed/domain/feed/dto/FindFeedDto.java
- src/main/java/com/depromeet/stonebed/domain/feed/dto/response/v1/FeedContentGetResponse.java
- src/main/java/com/depromeet/stonebed/domain/feed/dto/response/v2/FeedContentGetResponseV2.java
- src/main/java/com/depromeet/stonebed/domain/missionRecord/domain/MissionRecord.java
- src/test/java/com/depromeet/stonebed/domain/auth/application/AuthServiceTest.java
- src/test/java/com/depromeet/stonebed/domain/comment/application/CommentServiceTest.java
- src/test/java/com/depromeet/stonebed/domain/feed/application/FeedServiceTest.java
- close #315 
- comment-record mapping에 대한 연관관계 삭제
- recordId를 저장하며 직접 proxy접근이 아니도록 수정
- 회원탈퇴 시 comment 테이블의 writerId는 null로 처리되도록 수정
-
-
> fix: 회원 탈퇴 시 탈퇴자 댓글 예외 처리

- .github/workflows/develop-deploy.yml
- .github/workflows/production-deploy.yml
- src/main/java/com/depromeet/stonebed/domain/comment/application/CommentService.java
- src/test/java/com/depromeet/stonebed/domain/comment/application/CommentServiceTest.java
- close #321 
- workflow_dispatch의 inputs를 받아 유연하게 배포처리를 할 수 있도록 구성
-
-
> chore: 배포 버전 workflow 추가 구성
